#!/bin/bash
#
# Copyright (c) 2021 RethinkDNS and its authors.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -eux

# refs:
# github.com/shiguredo/shiguredo-webrtc-android/blob/8f5bea7/prepareAar.sh
# github.com/zoff99/pkgs_guardianprojectNetcipher/blob/52d9a59/jitpack.yml
# repo: jitpack.io/com/github/$GROUP/$ARTIFACT/$VERSION/
# logs: jitpack.io/com/github/$GROUP/$ARTIFACT/$VERSION/build.log

# from: github.com/ignoramous/outline-go-tun2socks/tree/jpac2
# maven.apache.org/plugins/maven-install-plugin/examples/installing-secondary-artifacts.html
mvn install:install-file \
    -Dfile=${FOUT} \
    -Dpackaging=${PACK} \
    -Dversion=${VERSION} \
    -DgroupId=${GROUP} \
    -DartifactId=${ARTIFACT} \
    -Dsources=${SOURCES}
#    -Dclassifier=${CLASSFULL} \
# usage: docs.gradle.org/current/userguide/dependency_management.html
mvn -X install:install-file \
    -Dfile=${FOUTDBG} \
    -Dpackaging=${PACK} \
    -Dversion=${VERSION} \
    -DgroupId=${GROUP} \
    -DartifactId=${ARTIFACT} \
    -Dclassifier=${CLASSDBG} \
    -Dsources=${SOURCES}