#!/bin/bash

set -eux

# refs:
# github.com/shiguredo/shiguredo-webrtc-android/blob/8f5bea7/prepareAar.sh
# github.com/zoff99/pkgs_guardianprojectNetcipher/blob/52d9a59/jitpack.yml
# repo: jitpack.io/com/github/$GROUP/$ARTIFACT/$VERSION/
# logs: jitpack.io/com/github/$GROUP/$ARTIFACT/$VERSION/build.log

mvn install:install-file \
    -Dfile=${FOUT} \
    -Dpackaging=${PACK} \
    -Dversion=${VERSION} \
    -DgroupId=${GROUP} \
    -DartifactId=${ARTIFACT}
